//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryLogic.ModelProviders.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Authors = new HashSet<Author>();
            this.WordEntries = new HashSet<WordEntry>();
        }
    
        public int Book_ID { get; set; }
        public string Name { get; set; }
        public int Language_ID { get; set; }
        public int NumberOfPages { get; set; }
        public int Format_ID { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual Format Format { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<WordEntry> WordEntries { get; set; }
    }
}
