//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryLogic.ModelProviders.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearnDictionaryEntities : DbContext
    {
        public LearnDictionaryEntities()
            : base("name=LearnDictionaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Format> Formats { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LearnStatistic> LearnStatistics { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<WordMeaning> WordMeanings { get; set; }
        public virtual DbSet<WordMeaningStatistic> WordMeaningStatistics { get; set; }
        public virtual DbSet<WordEntry> WordEntries { get; set; }
        public virtual DbSet<SpeechPart> SpeechParts { get; set; }
    }
}
