//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryLogic.ModelProviders.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Books = new HashSet<Book>();
            this.Words = new HashSet<Word>();
        }
    
        public int Language_ID { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Word> Words { get; set; }
    }
}
